version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    labels:
      - dependencies
      - frontend

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    labels:
      - dependencies
      - backend
